export type ChartMapping = {
  blockId: string;
  chartTitle: string;
};

export type TableRowMapping = {
  blockId: string;
  sourceCells: string[]; // e.g. ["C5", "D5", "E5", "F5"], left-to-right column order
};

export type GenerateInput = {
  dataSourceTab: string;
  preExportFunctionName?: string; // must already exist elsewhere in the target Apps Script project
  charts: ChartMapping[];
  tableRows: TableRowMapping[];
};

// Generates the full Notion.gs text for a connector. This mirrors
// apps-script/Code.gs in this repo exactly, except runPreExportStep()'s
// body is templated: a literal call to the given function name if one was
// provided, or a no-op success if not. This is deliberately NOT dynamic
// reflection (e.g. this[name]()) at runtime — a plain literal function
// call generated at setup time is more robust across Apps Script's
// execution model, and is easier for a human to read afterward.
export function generateNotionGsCode(preExportFunctionName?: string): string {
  const trimmedName = preExportFunctionName?.trim();

  const preExportBody = trimmedName
    ? `  return ${trimmedName}();`
    : `  return { success: true }; // no pre-export function configured for this connector`;

  const preExportDocs = trimmedName
    ? `This connector's pre-export step: runs ${trimmedName}() (must already\n * exist elsewhere in this Apps Script project) and returns its result\n * as-is.`
    : `This connector has no pre-export step configured, so this is always a\n * no-op success. The middleware calls ?action=runPreExport unconditionally\n * on every sync, so this must always be safe to call.`;

  return `/**
 * Web App entry point for the Notion-Updater middleware. Deployed as a
 * Google Apps Script Web App; see doGet() below for the actions it serves.
 *
 * Generated by the Notion-Updater setup wizard (/setup).
 *
 * IMPORTANT: Deploy this as a Web App (Deploy > New deployment > Web app)
 * with "Execute as: Me" and "Who has access: Anyone," then register that
 * deployment URL as this connector's appsScriptUrl in connectors.json.
 */

const CONFIG2 = {
  MAPPING_SHEET_NAME: "Mapping",
};

/**
 * This script serves TWO actions via its Web App doGet, selected by the
 * ?action= query param:
 *
 *   ?action=runPreExport   -> runs this connector's pre-export step (see
 *                              runPreExportStep() below), headlessly.
 *                              Returns { success, error?, phase? }.
 *   (default / no action)  -> reads the "Mapping" sheet and returns
 *                              everything it points at, resolved and
 *                              ready to write directly to Notion:
 *                              {
 *                                "tableRows": [ { "blockId", "values": [...] } ],
 *                                "charts":    [ { "blockId", "imageBase64" } ],
 *                                "warnings":  [ "..." ]
 *                              }
 *
 * There is no anchor-text searching on the Notion side at all — every
 * chart and table row this script returns already carries the exact Notion
 * block ID it should be written to (see the Mapping sheet). This script
 * does NOT talk to Notion directly — the middleware owns Vercel Blob
 * uploads and all Notion API calls.
 */
function doGet(e) {
  try {
    const action = (e && e.parameter && e.parameter.action) || 'exportMapped';

    if (action === 'runPreExport') {
      const result = runPreExportStep();
      return ContentService
        .createTextOutput(JSON.stringify(result))
        .setMimeType(ContentService.MimeType.JSON);
    }

    const result = exportMappedDataAsJson();
    return ContentService
      .createTextOutput(JSON.stringify(result))
      .setMimeType(ContentService.MimeType.JSON);
  } catch (err) {
    return ContentService
      .createTextOutput(JSON.stringify({ error: String(err) }))
      .setMimeType(ContentService.MimeType.JSON);
  }
}

/**
 * ${preExportDocs}
 */
function runPreExportStep() {
${preExportBody}
}

/**
 * Reads the "Mapping" sheet and resolves it into everything the middleware
 * needs to write directly to Notion. Expected layout:
 *
 *   B1: <name of the sheet charts/cells live on>
 *
 *   For each row anywhere on the sheet:
 *     - Column A == "Row Block ID" AND column B non-empty
 *         -> a table row mapping. B = the Notion table_row block ID.
 *            Every non-empty cell from column C onward is a source cell
 *            reference (e.g. "C5") on the Data Source Tab, in left-to-right
 *            order — this determines column order in the Notion row.
 *     - Column A == "Block ID" AND column B non-empty
 *         -> a chart mapping. B = the Notion image block ID. C = the
 *            chart's title in Google Sheets.
 *     - Anything else (including a label row with an EMPTY column B) is
 *       skipped — this is how a human-readable reference row can coexist
 *       with real mapping rows on the same sheet.
 */
function readMappingSheet() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const mappingSheet = ss.getSheetByName(CONFIG2.MAPPING_SHEET_NAME);
  if (!mappingSheet) {
    throw new Error("Could not find '" + CONFIG2.MAPPING_SHEET_NAME + "' sheet.");
  }

  const dataSourceTabName = mappingSheet.getRange('B1').getDisplayValue().trim();
  if (!dataSourceTabName) {
    throw new Error('Mapping sheet cell B1 ("Data Source Tab") is empty.');
  }
  const dataSheet = ss.getSheetByName(dataSourceTabName);
  if (!dataSheet) {
    throw new Error("Could not find data source sheet '" + dataSourceTabName + "' referenced in Mapping!B1.");
  }

  const mappingValues = mappingSheet.getDataRange().getValues();
  const tableRowMappings = [];
  const chartMappings = [];
  const warnings = [];

  for (let i = 0; i < mappingValues.length; i++) {
    const row = mappingValues[i];
    const label = String(row[0]).trim();
    const blockId = String(row[1]).trim();

    if (!blockId) continue;

    if (label === 'Row Block ID') {
      const sourceCellRefs = [];
      for (let c = 2; c < row.length; c++) {
        const cellRef = String(row[c]).trim();
        if (cellRef) sourceCellRefs.push(cellRef);
      }
      if (sourceCellRefs.length === 0) {
        const warning = 'Row Block ID "' + blockId + '" (Mapping row ' + (i + 1) + ') has no source cell references — skipped.';
        Logger.log('⚠️ ' + warning);
        warnings.push(warning);
        continue;
      }
      tableRowMappings.push({ blockId: blockId, sourceCellRefs: sourceCellRefs });
    } else if (label === 'Block ID') {
      const chartTitle = String(row[2]).trim();
      if (!chartTitle) {
        const warning = 'Block ID "' + blockId + '" (Mapping row ' + (i + 1) + ') has no chart title in column C — skipped.';
        Logger.log('⚠️ ' + warning);
        warnings.push(warning);
        continue;
      }
      chartMappings.push({ blockId: blockId, chartTitle: chartTitle });
    }
  }

  console.log(
    'Mapping sheet parsed: ' + tableRowMappings.length + ' table row mapping(s), ' +
    chartMappings.length + ' chart mapping(s). Data source tab: "' + dataSourceTabName + '".'
  );

  return { dataSheet: dataSheet, tableRowMappings: tableRowMappings, chartMappings: chartMappings, warnings: warnings };
}

function exportMappedDataAsJson() {
  const tStart = Date.now();
  const parsed = readMappingSheet();

  const tableRows = parsed.tableRowMappings.map(function (mapping) {
    const values = mapping.sourceCellRefs.map(function (ref) {
      return parsed.dataSheet.getRange(ref).getDisplayValue();
    });
    return { blockId: mapping.blockId, values: values };
  });

  const chartResult = exportMappedCharts(parsed.dataSheet, parsed.chartMappings);
  const warnings = parsed.warnings.concat(chartResult.warnings);

  console.log('[TIMING] exportMappedDataAsJson total: ' + (Date.now() - tStart) + 'ms');
  return { tableRows: tableRows, charts: chartResult.charts, warnings: warnings };
}

/**
 * Resolves each chart mapping's title to an actual chart object on the data
 * source sheet, then exports it as base64 PNG via a temporary Slides
 * presentation (chart.getAs('image/png') directly is a documented Apps
 * Script rendering quirk that doesn't always reproduce the chart's actual
 * on-screen appearance in Sheets — e.g. gridlines can render incorrectly).
 */
function exportMappedCharts(dataSheet, chartMappings) {
  const warnings = [];
  if (chartMappings.length === 0) return { charts: [], warnings: warnings };

  const allCharts = dataSheet.getCharts();
  const chartsByTitle = {};
  for (let i = 0; i < allCharts.length; i++) {
    const title = allCharts[i].getOptions().get('title');
    if (title) chartsByTitle[title] = allCharts[i];
  }

  const result = [];
  const tempPresentation = SlidesApp.create('__chart_export_temp_' + new Date().getTime());

  try {
    const slide = tempPresentation.getSlides()[0];

    for (let i = 0; i < chartMappings.length; i++) {
      const mapping = chartMappings[i];
      const chart = chartsByTitle[mapping.chartTitle];
      if (!chart) {
        const warning =
          'No chart titled "' + mapping.chartTitle + '" found on sheet "' + dataSheet.getName() +
          '" (available: ' + Object.keys(chartsByTitle).join(', ') + ') — skipped block ' + mapping.blockId + '.';
        Logger.log('⚠️ ' + warning);
        warnings.push(warning);
        continue;
      }

      const insertedChart = slide.insertSheetsChartAsImage(chart);
      const imageBlob = insertedChart.getAs('image/png');
      const base64Data = Utilities.base64Encode(imageBlob.getBytes());
      insertedChart.remove();

      result.push({ blockId: mapping.blockId, imageBase64: base64Data });
    }
  } finally {
    DriveApp.getFileById(tempPresentation.getId()).setTrashed(true);
  }

  return { charts: result, warnings: warnings };
}
`;
}

// Generates the Mapping sheet rows exactly as they should be pasted in,
// starting at row 1. Matches the layout convention already in use:
// B1 = data source tab name, then a "Tables" section, then a "Charts"
// section, each with one label/reference row followed by real mapping rows.
export function generateMappingRows(input: GenerateInput): string[][] {
  const rows: string[][] = [];

  rows.push(['Data Source Tab', input.dataSourceTab]);
  rows.push(['']);

  if (input.tableRows.length > 0) {
    rows.push(['Tables']);
    const maxCols = Math.max(...input.tableRows.map(r => r.sourceCells.length));
    // Reference/label row: shows column intent, but column B is left
    // blank on purpose so the parser skips it (see readMappingSheet()).
    rows.push(['Row Block ID', '', ...Array(maxCols).fill('')]);
    for (const row of input.tableRows) {
      rows.push(['Row Block ID', row.blockId, ...row.sourceCells]);
    }
    rows.push(['']);
  }

  if (input.charts.length > 0) {
    rows.push(['Charts']);
    for (const chart of input.charts) {
      rows.push(['Block ID', chart.blockId, chart.chartTitle]);
    }
  }

  return rows;
}
